-- ============================================================================
-- LUCE Real Estate — Generador de contenido para redes sociales
-- Proyecto Supabase: "Cerebro Telegram" (lrxwvyilfobwyndikqpq)
-- Aplicada el 2026-07-29 como migración `contenido_redes_campos_y_publicaciones`
--
-- Este archivo queda como documentación de lo que se aplicó (el repo no usa
-- migraciones versionadas; mismo criterio que `security-policies.sql`).
-- Todo es idempotente: se puede volver a ejecutar sin efectos secundarios.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Campos que faltaban en `propiedades` para poder generar contenido
--    Todos con DEFAULT o NULL: `PropertyForm` manda el objeto completo en cada
--    insert/update y las propiedades existentes no deben romperse.
-- ----------------------------------------------------------------------------
alter table public.propiedades
  add column if not exists metros_terreno   numeric default 0,
  add column if not exists estacionamientos integer default 0,
  add column if not exists amenidades       jsonb   default '[]'::jsonb,
  add column if not exists asesor_telefono  text,
  add column if not exists asesor_email     text;

comment on column public.propiedades.metros_cuadrados is 'Superficie construida en m2';
comment on column public.propiedades.metros_terreno   is 'Superficie de terreno en m2';
comment on column public.propiedades.amenidades       is 'Array JSON de slugs: ["alberca","jardin","seguridad_24h",...]';
comment on column public.propiedades.asesor_telefono  is 'Telefono de contacto del asesor, se publica en el contenido';
comment on column public.propiedades.asesor_email     is 'Email de contacto del asesor, se publica en el contenido';

-- Nota: `tipo` y `tipo_oferta` son text sin CHECK constraint, así que el valor
-- nuevo "penthouse" no requiere cambios en la base de datos (solo UI + tipos TS).

-- ----------------------------------------------------------------------------
-- 2. Historial de contenido generado con IA
-- ----------------------------------------------------------------------------
create table if not exists public.publicaciones_generadas (
  id                   bigint generated by default as identity primary key,
  propiedad_id         integer not null references public.propiedades(id) on delete cascade,
  descripcion_generada text,
  copy_instagram       text,
  hashtags             jsonb default '[]'::jsonb,
  asesor               text,
  creado_por           uuid references auth.users(id) on delete set null,
  modelo               text,
  created_at           timestamptz default now()
);

create index if not exists publicaciones_generadas_propiedad_idx
  on public.publicaciones_generadas (propiedad_id, created_at desc);

alter table public.publicaciones_generadas enable row level security;

-- A diferencia de `propiedades` (que tiene lectura pública para la landing),
-- esto es contenido interno: solo usuarios autenticados del admin.
drop policy if exists publicaciones_select_auth on public.publicaciones_generadas;
create policy publicaciones_select_auth on public.publicaciones_generadas
  for select to authenticated using (true);

drop policy if exists publicaciones_insert_auth on public.publicaciones_generadas;
create policy publicaciones_insert_auth on public.publicaciones_generadas
  for insert to authenticated with check (true);

drop policy if exists publicaciones_delete_auth on public.publicaciones_generadas;
create policy publicaciones_delete_auth on public.publicaciones_generadas
  for delete to authenticated using (true);

-- ----------------------------------------------------------------------------
-- 3. Carruseles de Instagram archivados
--    (migración `carruseles_guardados_en_historial`, 2026-08-02)
--
--    Las láminas se guardan en Storage y se cuelgan de la publicación, para que
--    el historial conserve lo que realmente se publicó aunque la propiedad
--    cambie después.
-- ----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('publicaciones', 'publicaciones', true)
on conflict (id) do nothing;

-- Público igual que fotospropiedades: son imágenes hechas para publicarse.
drop policy if exists "Public read publicaciones" on storage.objects;
create policy "Public read publicaciones" on storage.objects
  for select to public using (bucket_id = 'publicaciones');

drop policy if exists "Authenticated upload publicaciones" on storage.objects;
create policy "Authenticated upload publicaciones" on storage.objects
  for insert to authenticated with check (bucket_id = 'publicaciones');

-- UPDATE hace falta porque al regenerar un carrusel se sube con upsert sobre
-- la misma ruta, y eso es un UPDATE en storage.objects, no un INSERT.
drop policy if exists "Authenticated update publicaciones" on storage.objects;
create policy "Authenticated update publicaciones" on storage.objects
  for update to authenticated using (bucket_id = 'publicaciones');

drop policy if exists "Authenticated delete publicaciones" on storage.objects;
create policy "Authenticated delete publicaciones" on storage.objects
  for delete to authenticated using (bucket_id = 'publicaciones');

alter table public.publicaciones_generadas
  add column if not exists imagenes jsonb default '[]'::jsonb;

comment on column public.publicaciones_generadas.imagenes is
  'Laminas del carrusel de Instagram ya generadas, en orden: [{nombre, url}]';

-- Ruta de las láminas: carruseles/{propiedad_id}/{publicacion_id}/01-portada.jpg

-- ----------------------------------------------------------------------------
-- 4. Secretos que hay que poner A MANO en el dashboard de Supabase
--    (Project Settings → Edge Functions → Secrets). El MCP no puede escribirlos.
--
--    OPENAI_API_KEY   (obligatorio) — clave de platform.openai.com
--    OPENAI_MODEL     (opcional)    — por defecto gpt-4o-mini
-- ----------------------------------------------------------------------------
