-- ============================================================================
-- LUCE Real Estate — Generador de contenido para redes sociales
-- Proyecto Supabase: "Cerebro Telegram" (lrxwvyilfobwyndikqpq)
-- Aplicada el 2026-07-29 como migración `contenido_redes_campos_y_publicaciones`
--
-- Este archivo queda como documentación de lo que se aplicó (el repo no usa
-- migraciones versionadas; mismo criterio que `security-policies.sql`).
-- Todo es idempotente: se puede volver a ejecutar sin efectos secundarios.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Campos que faltaban en `propiedades` para poder generar contenido
--    Todos con DEFAULT o NULL: `PropertyForm` manda el objeto completo en cada
--    insert/update y las propiedades existentes no deben romperse.
-- ----------------------------------------------------------------------------
alter table public.propiedades
  add column if not exists metros_terreno   numeric default 0,
  add column if not exists estacionamientos integer default 0,
  add column if not exists amenidades       jsonb   default '[]'::jsonb,
  add column if not exists asesor_telefono  text,
  add column if not exists asesor_email     text;

comment on column public.propiedades.metros_cuadrados is 'Superficie construida en m2';
comment on column public.propiedades.metros_terreno   is 'Superficie de terreno en m2';
comment on column public.propiedades.amenidades       is 'Array JSON de slugs: ["alberca","jardin","seguridad_24h",...]';
comment on column public.propiedades.asesor_telefono  is 'Telefono de contacto del asesor, se publica en el contenido';
comment on column public.propiedades.asesor_email     is 'Email de contacto del asesor, se publica en el contenido';

-- Nota: `tipo` y `tipo_oferta` son text sin CHECK constraint, así que el valor
-- nuevo "penthouse" no requiere cambios en la base de datos (solo UI + tipos TS).

-- ----------------------------------------------------------------------------
-- 2. Historial de contenido generado con IA
-- ----------------------------------------------------------------------------
create table if not exists public.publicaciones_generadas (
  id                   bigint generated by default as identity primary key,
  propiedad_id         integer not null references public.propiedades(id) on delete cascade,
  descripcion_generada text,
  copy_instagram       text,
  hashtags             jsonb default '[]'::jsonb,
  asesor               text,
  creado_por           uuid references auth.users(id) on delete set null,
  modelo               text,
  created_at           timestamptz default now()
);

create index if not exists publicaciones_generadas_propiedad_idx
  on public.publicaciones_generadas (propiedad_id, created_at desc);

alter table public.publicaciones_generadas enable row level security;

-- A diferencia de `propiedades` (que tiene lectura pública para la landing),
-- esto es contenido interno: solo usuarios autenticados del admin.
drop policy if exists publicaciones_select_auth on public.publicaciones_generadas;
create policy publicaciones_select_auth on public.publicaciones_generadas
  for select to authenticated using (true);

drop policy if exists publicaciones_insert_auth on public.publicaciones_generadas;
create policy publicaciones_insert_auth on public.publicaciones_generadas
  for insert to authenticated with check (true);

drop policy if exists publicaciones_delete_auth on public.publicaciones_generadas;
create policy publicaciones_delete_auth on public.publicaciones_generadas
  for delete to authenticated using (true);

-- ----------------------------------------------------------------------------
-- 3. Secretos que hay que poner A MANO en el dashboard de Supabase
--    (Project Settings → Edge Functions → Secrets). El MCP no puede escribirlos.
--
--    OPENAI_API_KEY   (obligatorio) — clave de platform.openai.com
--    OPENAI_MODEL     (opcional)    — por defecto gpt-4o-mini
-- ----------------------------------------------------------------------------
